### ISSUE TITLE
Convert p to look like H in detected tags

### ISSUE THREAD

**Issue by GearsAD** [Affie/AprilTags.jl#4]
H is an Array{Float64, 2}. Could we look at making p the same?

RIght now p is a NTuple{4,Tuple{Float64,Float64}}.

**Comment by Affie** [comment]
Definitely. In the wrapper part it is easiest to work with the NTuple, but its on my todo list for the AprilTag struct.

**Comment by Affie** [comment]
PR #5 should take care of this

**Comment by GearsAD** [comment]
:+1:
